# ──────────────────────────────────────────────────────────────
# GLOBAL DEFAULTS – used by every stage
# ──────────────────────────────────────────────────────────────
defaults:
  INPUT_CSV:   "C:/Users/Jason Pohl/OneDrive - Bond University/PhD/rff/NEW_DATA.csv"
  OUTPUT_ROOT: "C:/Users/Jason Pohl/OneDrive - Bond University/PhD/rff/outputs_rff"

  # ★── new pipeline-wide flags ───────────────────────────────
  include_transforms: true       # auto-create Log_/Sqrt_ twins for skewed ratios
  SAVE_FORMAT:       "csv"       # "csv" or "parquet"
  PURGE_OLD:         false       # delete older run folders after a successful run

  # bucket-winner selection
  SELECT_STAT:       "AvgRho"    # "AvgRho" | "AvgAUROC" | "AvgPR2" | "Composite"
  CompositeWeights:              # used only if SELECT_STAT == Composite
    rho:   0.5
    auroc: 0.3
    pr2:   0.2

  # snapshot-logit settings
  YEARS_BACK:        1           # snapshot spans FY-(swan-YEARS_BACK … swan-1)
  REG_STRENGTH:      0           # >0 → ridge/ lasso penalty (0 = none)

# ──────────────────────────────────────────────────────────────
# EVENT-SPECIFIC WINDOWS
# ──────────────────────────────────────────────────────────────
events:
  "2008":
    WIN_START: 2003
    WIN_END:   2012
